version: '3'

services:
  mynotesweb:
    build:
      context: ./MyNotesWeb
      dockerfile: Dockerfile  # Adjust this if your Dockerfile has a different name
    ports:
      - "4200:4200"
    depends_on:
      - mynotesserver

  mynotesserver:
    build:
      context: ./Server
      dockerfile: Dockerfile  # Adjust this if your Dockerfile has a different name
    ports:
      - "5000:5000"
